### ISSUE TITLE
JavaScript Track To Be Completed

### ISSUE THREAD

**Issue by dmcshehan** [dmcshehan/treehouse-flashcards#2]
## TODO 

*Courses that i need to complete Full Stack JavaScript Development track on Treehouse*

* [ ] Express Basics
* [ ] Mongo Basics
* [ ] Understanding Closures in JavaScript
* [ ] User Authentication With Express and Mongo
* [ ] Build a REST API With Express
* [ ] JavaScript Unit Testing

🎉 👍
